markdown: kramdown
safe: true
lsi: false
prose:
  siteurl: 'http://cfrconsultores.com'
permalink: pretty


url: http://cfrconsultores.com
baseurl:

# Site settings
title: CFR Consultores
email: carlos.reyes@cfrconsultores.com
description: "CFR Consultores."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 91B832
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Carlos Reyes
  pic: carlos
  position: Socio
  email: carlos.reyes@cfrconsultores.com
  slug: carlos-reyes

- name: Laura Alvarez Moser
  pic: laura
  position: Socia
  email: laura.alvarezmoser@cfrconsultores.com
  slug: laura-alvarez-moser

- name: María Fernanda Daguerre
  pic: mfernanda
  position: Socia
  email: fernanda.daguerre@cfrconsultores.com
  slug: maria-fernanda-daguerre

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
